# Sales Record Analysis
### Author: Corey Allen
### Exercise 2.E Using functions for analyzing data

This notebook analyzes a small sales dataset using Python functions.
Each function takes the full dataset as its first argument. 

In [146]:
sales_data = [
('Laptop', 'East', 1200.00),
('Phone', 'West', 850.00),
('Tablet', 'East', 400.00),
('Monitor', 'South', 650.00),
('Keyboard', 'West', 75.00),
('Laptop', 'South', 1150.00),
('Phone', 'East', 900.00),
('Tablet', 'West', 425.00),
('Monitor', 'East', 680.00),
('Keyboard', 'South', 80.00),
('Laptop', 'West', 1300.00),
('Phone', 'West', 820.00),
]

## Lab 1. Total sales by region 

In [45]:
def region_total(sales_data, region):
    return sum(sale_amount for product, reg, sale_amount in sales_data if reg == region)

In [79]:
print("\n EASTERN REGION TOTALS:")
print(region_total(sales_data, 'East')) # Sales total for eastern region
print("\n WESTERN REGION TOTALS:")
print(region_total(sales_data, 'West')) # Sales total for western region
print("\n SOUTHERN REGION TOTALS:")
print(region_total(sales_data, 'South')) # Sales total for southern region


 EASTERN REGION TOTALS:
3180.0

 WESTERN REGION TOTALS:
3470.0

 SOUTHERN REGION TOTALS:
1880.0


## Lab 2. Count of sales by region

In [72]:
def region_count(sales_data, region):
    return sum(1 for product, reg, sale_amount in sales_data if reg == region)

In [81]:
print("\n EASTERN COUNT:")
print(region_count(sales_data, "East"))
print("\n WESTERN COUNT:")
print(region_count(sales_data, "West"))
print("\n SOUTHERN COUNT:")
print(region_count(sales_data, "South"))
print("\n NORHTERN COUNT:")
print(region_count(sales_data, "North"))


 EASTERN COUNT:
4

 WESTERN COUNT:
5

 SOUTHERN COUNT:
3

 NORHTERN COUNT:
0


# Lab 4. Filter by sale amount

In [82]:
def sales_above(data, threshold):
    return [row for row in data if row[2] > threshold]

In [86]:
results = (sales_above(sales_data, 500))
for row in results:
    print(row)

('Laptop', 'East', 1200.0)
('Phone', 'West', 850.0)
('Monitor', 'South', 650.0)
('Laptop', 'South', 1150.0)
('Phone', 'East', 900.0)
('Monitor', 'East', 680.0)
('Laptop', 'West', 1300.0)
('Phone', 'West', 820.0)


In [89]:
def sales_below(data, threshold):
    return [row for row in data if row[2] < threshold]

In [99]:
print("\n*BONUS*:")
results = sales_below(sales_data, 500)
for row in results:
    print(row)


*BONUS*:
('Tablet', 'East', 400.0)
('Keyboard', 'West', 75.0)
('Tablet', 'West', 425.0)
('Keyboard', 'South', 80.0)


# Lab 5. Top and bottom scale

In [100]:
def top_sale(data):
    return max(data, key=lambda row: row[2])

In [101]:
print(top_sale(sales_data)) # prints the top sale

('Laptop', 'West', 1300.0)


In [102]:
def bottom_sale(data):
    return min(data, key=lambda row: row[2])

In [104]:
print(bottom_sale(sales_data))

('Keyboard', 'West', 75.0)


The top sale was a laptop in the western region sold for 1300.00  
The lowest sale was a keyboard in the western region sold for 75.00

# Lab 6. Apply a discount

In [107]:
def apply_discount(data, discount):
    return [
        (product, region, sale_amount * (1 - discount))
        for product, region, sale_amount in data
    ]

In [109]:
sale_discount = apply_discount(sales_data, 0.15) # applies 15% discount

In [112]:
# prints first 3 rows b4 discount
print("before discount:")
for row in sales_data[3]:
    print(row)

before discount:
Monitor
South
650.0


In [114]:
# Prints first three rows after discount
print("After discount:")
for row in sale_discount[3]:
    print(row)

After discount:
Monitor
South
552.5


# Lab 7. Unique regions

In [120]:
def unique_regions(data):
    return sorted(set((row[1] for row in sales_data)))

In [123]:
regions = unique_regions(sales_data)
print(regions)

['East', 'South', 'West']


This function could be useful in a large data set of say 1000 values. If I wanted to return all of the unique locations it would be too tedious to manually specify which regions to return. This function can be scaled up to any size.

# Lab 8. Region Summary

In [158]:
def region_summary(data, region):
    # Filters specific records for a given region
    region_data = [row for row in data if row[1] == region]

    # Summary Stats
    total = region_total(data, region)
    count = region_count(data, region)
    average = total / count if count else 0 
    top = top_sale(region_data)

    # Formatted report print statement
    print(f"\n === Sales summary for {region} region ===")
    print(f"Total Sales: ${total:.2f}")
    print(f"Number of Sales: {count}")
    print(f"Average Sale Amount: ${average:.2f}")

    print("\nTop Sale:")
    print(f"Product: {top[0]}")
    print(f"Region: {top[1]}")
    print(f"Amount: ${top[2]:.2f}")
    

In [159]:
region_summary(sales_data, "East")


 === Sales summary for East region ===
Total Sales: $3180.00
Number of Sales: 4
Average Sale Amount: $795.00

Top Sale:
Product: Laptop
Region: East
Amount: $1200.00


# Lab 9. Full Summary

In [162]:
for region in unique_regions(sales_data):
    region_summary(sales_data, region)


 === Sales summary for East region ===
Total Sales: $3180.00
Number of Sales: 4
Average Sale Amount: $795.00

Top Sale:
Product: Laptop
Region: East
Amount: $1200.00

 === Sales summary for South region ===
Total Sales: $1880.00
Number of Sales: 3
Average Sale Amount: $626.67

Top Sale:
Product: Laptop
Region: South
Amount: $1150.00

 === Sales summary for West region ===
Total Sales: $3470.00
Number of Sales: 5
Average Sale Amount: $694.00

Top Sale:
Product: Laptop
Region: West
Amount: $1300.00


This lab showed me how to build a sales analysis pipeline using csv data from the (sales_data) list. In addition to parsing the data, I formatted a comprehensive breakdown of the data that is cleanly formatted. It was difficult to figure out the minute details of the lab but by using external resources I was able to figure it out and gain a reasonable understanding of how all of the code functions together.